# Generated by Django 5.1.1 on 2024-10-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_loc_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc_user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
