# Generated by Django 5.1.1 on 2024-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_loc_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
