# Generated by Django 5.1.1 on 2024-11-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_category_products_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
